server: 
  port: 8080

spring:
  application:
    name: organization-service
  profiles: 
    active: local
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create  
#    generate-ddl: true
    
logging:
  level:
    org:
      springframework : info
    com:
      ziumks : info
      zaxxer: DEBUG
    root : ERROR 

mybatis:
  type-aliases-package: com.ziumks.organization.model
  type-handlers-package: com.ziumks.organization.dao
  configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30    
#mysql:
#  db:
#    jdbc:
#      driver: com.ziumks.organization.Driver
#      url: jdbc:mysql://localhost/test
